# Generated by Django 5.1.3 on 2024-11-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoservi', '0003_rename_servicerequest_servicio_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
