# Generated by Django 5.0.6 on 2024-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoservi', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
