# Generated by Django 5.0.6 on 2024-11-28 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoservi', '0005_servicio_completado_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
